"""Askii — the Python client for the Askii platform API.

Quickstart::

    from askii import AsyncAskii

    async with AsyncAskii(token=mpass_jwt) as client:
        keys = await client.keys.list()
        for k in keys.keys:
            print(k.key_name, k.spend)

See ``README.md`` for full usage, configuration, caching, hooks, and CLI.
"""

from askii._cache import Cache, build_cache_key, build_resource_prefix
from askii._cache.memory import InMemoryCache
from askii._client.async_client import AsyncAskii
from askii._client.sync_client import Askii
from askii._config import (
    DEFAULT_BASE_URL,
    DEFAULT_MAX_RETRIES,
    DEFAULT_TIMEOUT_SECONDS,
    AskiiConfig,
)
from askii._errors import (
    AskiiAPIError,
    AskiiAuthError,
    AskiiConnectionError,
    AskiiError,
    AskiiNotFoundError,
    AskiiRateLimitError,
    AskiiServerError,
    AskiiTimeoutError,
    AskiiTransportError,
    AskiiValidationError,
    FieldError,
)
from askii._hooks import Hooks, RequestEvent, ResponseEvent, RetryEvent
from askii._logging import (
    bind_correlation_id,
    configure_logging,
    get_correlation_id,
    reset_correlation_id,
)
from askii._token import TokenSource
from askii.models import (
    AvailableModel,
    AvailableModelsResponse,
    GetKeyConfigRequest,
    KeyConfig,
    KeyInfo,
    ListKeysResponse,
    MemoryMode,
    ProvisionKeyRequest,
    ProvisionKeyResponse,
    RevokeKeyRequest,
    RevokeKeyResponse,
    UpdateKeyModelRequest,
    UpdateKeyModelResponse,
)

try:  # generated by hatch-vcs at build time
    from askii._version import __version__
except ImportError:  # pragma: no cover — present after build, missing during raw checkout
    __version__ = "0.0.0+local"

__all__ = [
    # Clients
    "AsyncAskii",
    "Askii",
    # Configuration
    "AskiiConfig",
    "TokenSource",
    "DEFAULT_BASE_URL",
    "DEFAULT_TIMEOUT_SECONDS",
    "DEFAULT_MAX_RETRIES",
    # Hooks / events
    "Hooks",
    "RequestEvent",
    "ResponseEvent",
    "RetryEvent",
    # Cache
    "Cache",
    "InMemoryCache",
    "build_cache_key",
    "build_resource_prefix",
    # Logging
    "configure_logging",
    "bind_correlation_id",
    "reset_correlation_id",
    "get_correlation_id",
    # Errors
    "AskiiError",
    "AskiiTransportError",
    "AskiiConnectionError",
    "AskiiTimeoutError",
    "AskiiAPIError",
    "AskiiAuthError",
    "AskiiNotFoundError",
    "AskiiValidationError",
    "AskiiRateLimitError",
    "AskiiServerError",
    "FieldError",
    # Models
    "MemoryMode",
    "ProvisionKeyRequest",
    "ProvisionKeyResponse",
    "KeyInfo",
    "ListKeysResponse",
    "RevokeKeyRequest",
    "RevokeKeyResponse",
    "GetKeyConfigRequest",
    "KeyConfig",
    "UpdateKeyModelRequest",
    "UpdateKeyModelResponse",
    "AvailableModel",
    "AvailableModelsResponse",
    # Misc
    "__version__",
]
